name: inject_generator
version: 1.0.0-alpha
description: Dev-time dependency for package:inject.
authors:
  - Matan Lurey <matanl@google.com>
  - Yegor Jbanov <yjbanov@google.com>
homepage: https://pub.dartlang.org/packages/inject

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  analyzer: ^0.41.1
  build: ^1.5.0
  code_builder: ^3.4.1
  collection: ^1.14.7
  dart_style: ^1.3.7
  logging: ^0.11.3+1
  meta: ^1.1.2
  path: ^1.5.1
  quiver: ^2.1.3
  stack_trace: ^1.9.2

dev_dependencies:
  build_runner: ^1.10.3
  build_test: ^1.2.2
  inject:
    path: ../inject
  test: ^1.15.4
